version: "3.4"
services:
  winstonformattester:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: winstonformattester
    container_name: winstonformattester
    platform: linux/amd64
    volumes:
      - .:/srv/
    tty: true